# Generated by Django 5.0.6 on 2026-05-29 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='#6c757d', help_text='Color hex (ej. #0d6efd) para la etiqueta visual', max_length=7)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('contacto_principal', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Describe lo más detalladamente posible')),
                ('ubicacion_especifica', models.CharField(blank=True, help_text='Ej: Habitación 305, lobby, restaurante, área de piscina', max_length=200)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_progreso', 'En progreso'), ('en_espera', 'En espera'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], db_index=True, default='abierto', max_length=15)),
                ('solicitante_nombre', models.CharField(help_text='Nombre de quien reporta (si no tiene cuenta)', max_length=100)),
                ('solicitante_email', models.EmailField(blank=True, max_length=254)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('primera_respuesta_en', models.DateTimeField(blank=True, null=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.categoria')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.hotel')),
                ('solicitante_usuario', models.ForeignKey(blank=True, help_text='Usuario del sistema, si el reporte fue hecho con cuenta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(blank=True, help_text='Se guarda el nombre por si el usuario se borra después', max_length=150)),
                ('accion', models.CharField(choices=[('crear', 'Ticket creado'), ('editar', 'Datos editados'), ('cambio_estado', 'Cambio de estado'), ('cambio_prioridad', 'Cambio de prioridad'), ('asignar', 'Asignación'), ('comentar', 'Comentario añadido'), ('resolver', 'Resuelto'), ('cerrar', 'Cerrado'), ('reabrir', 'Reabierto')], max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('interno', models.BooleanField(default=False, help_text='Si está marcado, solo lo ven los técnicos (no el solicitante)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.ticket')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado', '-creado_en'], name='tickets_tic_estado_94496d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['hotel', 'estado'], name='tickets_tic_hotel_i_2228b7_idx'),
        ),
    ]
