# Generated by Django 5.0.6 on 2026-06-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='solicitante_email',
        ),
    ]
