# Generated by Django 5.0.6 on 2026-06-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_solicitante_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solicitante_email',
            field=models.EmailField(default='', help_text='Correo del solicitante para notificaciones', max_length=254),
        ),
    ]
