# Generated by Django 5.0.6 on 2026-06-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_solicitante_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='solicitante_usuario',
        ),
    ]
