# Generated by Django 5.0.6 on 2026-06-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_hotel_oficina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='prioridad',
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('crear', 'Ticket creado'), ('editar', 'Datos editados'), ('cambio_estado', 'Cambio de estado'), ('asignar', 'Asignación'), ('comentar', 'Comentario añadido'), ('resolver', 'Resuelto'), ('cerrar', 'Cerrado'), ('reabrir', 'Reabierto')], max_length=20),
        ),
    ]
